Repository ethyca/fidesops, pull requests merged in 2022-09, with the labels that each got.

#1260 Fix for pytest-asyncio bug
  CHANGELOG.md
  tests/ops/integration_tests/saas/request_override/test_mailchimp_override_task.py
  tests/ops/integration_tests/saas/test_adobe_campaign_task.py
  tests/ops/integration_tests/saas/test_datadog_task.py
  tests/ops/integration_tests/saas/test_hubspot_task.py
  tests/ops/integration_tests/saas/test_logi_id_task.py
  tests/ops/integration_tests/saas/test_mailchimp_task.py
  tests/ops/integration_tests/saas/test_outreach_task.py
  tests/ops/integration_tests/saas/test_salesforce_task.py
  tests/ops/integration_tests/saas/test_segment_task.py
  tests/ops/integration_tests/saas/test_sendgrid_task.py
  tests/ops/integration_tests/saas/test_sentry_task.py
  tests/ops/integration_tests/saas/test_shopify_task.py
  tests/ops/integration_tests/saas/test_stripe_task.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
  tests/ops/integration_tests/test_execution.py
  tests/ops/integration_tests/test_integration_email.py
  tests/ops/integration_tests/test_manual_task.py
  tests/ops/integration_tests/test_mongo_task.py
  tests/ops/integration_tests/test_sql_task.py
Labels: run unsafe ci checks

#1254 Refactor strategy instantiation for more extensitiliby
  CHANGELOG.md
  docs/fidesops/docs/guides/masking_strategies.md
  src/fidesops/ops/api/v1/endpoints/masking_endpoints.py
  src/fidesops/ops/api/v1/endpoints/oauth_endpoints.py
  src/fidesops/ops/api/v1/endpoints/saas_config_endpoints.py
  src/fidesops/ops/migrations/versions/55d61eb8ed12_add_default_policies.py
  src/fidesops/ops/schemas/saas/saas_config.py
  src/fidesops/ops/service/authentication/__init__.py
  src/fidesops/ops/service/authentication/authentication_strategy.py
  src/fidesops/ops/service/authentication/authentication_strategy_basic.py
  src/fidesops/ops/service/authentication/authentication_strategy_bearer.py
  src/fidesops/ops/service/authentication/authentication_strategy_factory.py
  src/fidesops/ops/service/authentication/authentication_strategy_oauth2_authorization_code.py
  src/fidesops/ops/service/authentication/authentication_strategy_oauth2_client_credentials.py
  src/fidesops/ops/service/authentication/authentication_strategy_query_param.py
  src/fidesops/ops/service/connectors/query_config.py
  src/fidesops/ops/service/connectors/saas/authenticated_client.py
  src/fidesops/ops/service/connectors/saas_connector.py
  src/fidesops/ops/service/masking/strategy/masking_strategy.py
  src/fidesops/ops/service/masking/strategy/masking_strategy_aes_encrypt.py
  src/fidesops/ops/service/masking/strategy/masking_strategy_factory.py
  src/fidesops/ops/service/masking/strategy/masking_strategy_hash.py
  src/fidesops/ops/service/masking/strategy/masking_strategy_hmac.py
  src/fidesops/ops/service/masking/strategy/masking_strategy_nullify.py
  src/fidesops/ops/service/masking/strategy/masking_strategy_random_string_rewrite.py
  src/fidesops/ops/service/masking/strategy/masking_strategy_string_rewrite.py
  src/fidesops/ops/service/pagination/__init__.py
  src/fidesops/ops/service/pagination/pagination_strategy.py
  src/fidesops/ops/service/pagination/pagination_strategy_cursor.py
  src/fidesops/ops/service/pagination/pagination_strategy_factory.py
  src/fidesops/ops/service/pagination/pagination_strategy_link.py
  src/fidesops/ops/service/pagination/pagination_strategy_offset.py
  src/fidesops/ops/service/privacy_request/request_service.py
  src/fidesops/ops/service/processors/post_processor_strategy/__init__.py
  src/fidesops/ops/service/processors/post_processor_strategy/post_processor_strategy.py
  src/fidesops/ops/service/processors/post_processor_strategy/post_processor_strategy_factory.py
  src/fidesops/ops/service/processors/post_processor_strategy/post_processor_strategy_filter.py
  src/fidesops/ops/service/processors/post_processor_strategy/post_processor_strategy_unwrap.py
  src/fidesops/ops/service/strategy.py
  tests/ops/api/v1/endpoints/test_masking_endpoints.py
  tests/ops/api/v1/endpoints/test_policy_endpoints.py
  tests/ops/fixtures/application_fixtures.py
  tests/ops/models/test_policy.py
  tests/ops/service/authentication/test_authentication_strategy_basic.py
  tests/ops/service/authentication/test_authentication_strategy_bearer.py
  tests/ops/service/authentication/test_authentication_strategy_factory.py
  tests/ops/service/authentication/test_authentication_strategy_oauth2_authorization_code.py
  tests/ops/service/authentication/test_authentication_strategy_oauth2_client_credentials.py
  tests/ops/service/authentication/test_authentication_strategy_query_param.py
  tests/ops/service/connectors/test_queryconfig.py
  tests/ops/service/masking/strategy/test_masking_strategy_aes_encrypt.py
  tests/ops/service/masking/strategy/test_masking_strategy_factory.py
  tests/ops/service/masking/strategy/test_masking_strategy_hash.py
  tests/ops/service/masking/strategy/test_masking_strategy_hmac.py
  tests/ops/service/pagination/test_pagination_strategy_factory.py
  tests/ops/service/privacy_request/request_runner_service_test.py
  tests/ops/service/processors/post_processor_strategy/test_post_processor_strategy_factory.py
  tests/ops/service/test_strategy_retrieval.py
  tests/ops/util/encryption/test_secrets_util.py
Labels: run unsafe ci checks, Needs doc review, SaaSConnector

#1280 Fix typo
  CHANGELOG.md
  src/fidesops/ops/service/saas_request/saas_request_override_factory.py
Labels: run unsafe ci checks

#1275 Pass in Vault environment variables if they are present locally
  CHANGELOG.md
  docker-compose.yml
Labels: run unsafe ci checks

#1253 Improved param_value aggregation to support one-to-many relationships
  CHANGELOG.md
  data/saas/config/saas_example_config.yml
  data/saas/config/stripe_config.yml
  data/saas/dataset/saas_example_dataset.yml
  src/fidesops/ops/schemas/connection_configuration/connection_secrets_saas.py
  src/fidesops/ops/schemas/saas/saas_config.py
  src/fidesops/ops/service/connectors/saas_query_config.py
  src/fidesops/ops/util/saas_util.py
  tests/ops/api/v1/endpoints/test_saas_config_endpoints.py
  tests/ops/fixtures/saas/zendesk_fixtures.py
  tests/ops/fixtures/saas_example_fixtures.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
  tests/ops/models/test_saasconfig.py
  tests/ops/schemas/connection_configuration/test_connection_secrets_saas.py
  tests/ops/service/connectors/test_queryconfig.py
  tests/ops/service/connectors/test_saas_queryconfig.py
Labels: run unsafe ci checks

#1287 Bump python from 3.9.13 to 3.9.14
  CHANGELOG.md
  Dockerfile
Labels: run unsafe ci checks

#1289 1183 saas connectors shopify erasure
  CHANGELOG.md
  data/saas/config/shopify_config.yml
  data/saas/dataset/shopify_dataset.yml
  tests/ops/fixtures/saas/shopify_fixtures.py
  tests/ops/integration_tests/saas/test_shopify_task.py
Labels: run unsafe ci checks

#1307 Utility to update saas configs and datasets on system startup
  CHANGELOG.md
  src/fidesops/main.py
  src/fidesops/ops/api/deps.py
  src/fidesops/ops/api/v1/endpoints/saas_config_endpoints.py
  src/fidesops/ops/service/connectors/saas/connector_registry_service.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/connection_template_fixtures.py
  tests/ops/service/connectors/test_connector_registry_service.py
Labels: enhancement

#1324 Rename PrivacyRequestIdentity schema to Identity
  CHANGELOG.md
  scripts/create_test_data.py
  src/fidesops/ops/api/v1/endpoints/drp_endpoints.py
  src/fidesops/ops/models/privacy_request.py
  src/fidesops/ops/schemas/external_https.py
  src/fidesops/ops/schemas/privacy_request.py
  src/fidesops/ops/schemas/redis_cache.py
  src/fidesops/ops/service/drp/drp_fidesops_mapper.py
  src/fidesops/ops/service/privacy_request/onetrust_service.py
  src/fidesops/ops/service/privacy_request/request_service.py
  tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py
  tests/ops/fixtures/application_fixtures.py
  tests/ops/integration_tests/saas/request_override/test_mailchimp_override_task.py
  tests/ops/integration_tests/saas/test_adobe_campaign_task.py
  tests/ops/integration_tests/saas/test_auth0_task.py
  tests/ops/integration_tests/saas/test_datadog_task.py
  tests/ops/integration_tests/saas/test_hubspot_task.py
  tests/ops/integration_tests/saas/test_logi_id_task.py
  tests/ops/integration_tests/saas/test_mailchimp_task.py
  tests/ops/integration_tests/saas/test_outreach_task.py
  tests/ops/integration_tests/saas/test_salesforce_task.py
  tests/ops/integration_tests/saas/test_segment_task.py
  tests/ops/integration_tests/saas/test_sendgrid_task.py
  tests/ops/integration_tests/saas/test_sentry_task.py
  tests/ops/integration_tests/saas/test_shopify_task.py
  tests/ops/integration_tests/saas/test_stripe_task.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
  tests/ops/models/test_privacy_request.py
Labels: run unsafe ci checks

#1338 Explicitly install the `toml` package
  CHANGELOG.md
  requirements.txt
  src/fidesops/ops/core/config.py
Labels: bug, dev experience, run unsafe ci checks, dependencies, Tech Debt, fidesops-plus, python

#1352 Fixing Stripe Tests
  tests/ops/fixtures/saas/stripe_fixtures.py
  tests/ops/integration_tests/saas/test_stripe_task.py
Labels: run unsafe ci checks

#1345 v1.8.0 Release Checklist
  CHANGELOG.md
  clients/ops/admin-ui/src/flags.json
  docs/fidesops/docs/img/app_database.png
  scripts/quickstart.py
Labels: DON'T MERGE

#1331 334 api key authentication strategy
  CHANGELOG.md
  data/saas/config/datadog_config.yml
  data/saas/config/shopify_config.yml
  src/fidesops/ops/schemas/saas/strategy_configuration.py
  src/fidesops/ops/service/authentication/__init__.py
  src/fidesops/ops/service/authentication/authentication_strategy_api_key.py
  src/fidesops/ops/service/authentication/authentication_strategy_query_param.py
  tests/ops/service/authentication/test_authentication_strategy_api_key.py
  tests/ops/service/authentication/test_authentication_strategy_factory.py
  tests/ops/service/authentication/test_authentication_strategy_query_param.py
Labels: run unsafe ci checks

#1364 Updating offset pagination strategy to parse numeric strings as integers
  CHANGELOG.md
  src/fidesops/ops/service/pagination/pagination_strategy_offset.py
  tests/ops/service/pagination/test_pagination_strategy_offset.py
Labels: run unsafe ci checks

#1361 Rollbar (Access)
  data/saas/config/rollbar_config.yml
  data/saas/dataset/rollbar_dataset.yml
  data/saas/saas_connector_registry.toml
  pytest.ini
  src/fidesops/ops/schemas/saas/saas_config.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/rollbar_fixtures.py
  tests/ops/integration_tests/saas/test_rollbar_task.py
Labels: run unsafe ci checks

#1372 Removed connector from repository
  CHANGELOG.md
  data/saas/config/logi_id_config.yml
  data/saas/dataset/logi_id_dataset.yml
  data/saas/saas_connector_registry.toml
  docs/fidesops/docs/guides/connection_types.md
  pytest.ini
  src/fidesops/ops/schemas/saas/saas_config.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/logi_id_fixtures.py
  tests/ops/integration_tests/saas/test_logi_id_task.py
Labels: run unsafe ci checks

#1376 Enable retries on saas connectors for failures at the http request level
  CHANGELOG.md
  src/fidesops/ops/service/connectors/saas/authenticated_client.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
  tests/ops/service/connectors/saas/test_authenticated_client.py
Labels: enhancement, run unsafe ci checks

#1248 Braze Connector: Access Endpoints
  CHANGELOG.md
  data/saas/config/braze_config.yml
  data/saas/dataset/braze_dataset.yml
  pytest.ini
  src/fidesops/ops/schemas/saas/saas_config.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/braze_fixtures.py
  tests/ops/integration_tests/saas/test_braze_task.py
Labels: run unsafe ci checks

#1395 [#1393] Update Fidesops config with sane defaults where necessary
  CHANGELOG.md
  requirements.txt
  src/fidesops/ops/api/v1/endpoints/drp_endpoints.py
  src/fidesops/ops/core/config.py
Labels: run unsafe ci checks
