Repository ethyca/fidesops, pull requests merged in 2022-06, with the labels that each got.

#579 Improve configuration variable troubleshooting with DEBUG logs, more helpful errors, and unit tests
  CHANGELOG.md
  data/config/fidesops.toml
  docs/fidesops/docs/guides/configuration_reference.md
  fidesops.toml
  src/fidesops/core/config.py
  src/fidesops/main.py
  tests/core/__init__.py
  tests/core/test_config.py
Labels: run unsafe ci checks

#584 Adding "exact" and "case_sensitive" options to filter post-processor
  CHANGELOG.md
  docs/fidesops/docs/saas_connectors/saas_postprocessors.md
  src/fidesops/schemas/saas/strategy_configuration.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_filter.py
  tests/service/processors/post_processor_strategy/test_post_processor_strategy_filter.py
Labels: Needs doc review

#590 Add `__init__.py` files to all directories where they're currently missing
  CHANGELOG.md
  src/fidesops/service/connectors/saas/__init__.py
  src/migrations/__init__.py
  src/migrations/versions/__init__.py
  tests/fixtures/saas/__init__.py
  tests/integration_tests/saas/__init__.py
  tests/schemas/__init__.py
  tests/schemas/connection_configuration/__init__.py
  tests/scripts/__init__.py
  tests/service/pagination/__init__.py
  tests/service/processors/__init__.py
Labels: enhancement, dev experience, run unsafe ci checks

#578 Restart Graph from Failure [#574]
  CHANGELOG.md
  data/saas/dataset/hubspot_dataset.yml
  docs/fidesops/docs/guides/privacy_requests.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/api/v1/urn_registry.py
  src/fidesops/models/privacy_request.py
  src/fidesops/service/connectors/query_config.py
  src/fidesops/service/privacy_request/request_runner_service.py
  src/fidesops/task/graph_task.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
  tests/graph/test_graph.py
  tests/integration_tests/saas/test_stripe_task.py
  tests/integration_tests/test_integration_restart.py
  tests/integration_tests/test_sql_task.py
  tests/models/test_privacy_request.py
Labels: run unsafe ci checks

#617 Minor formatting fixes for SaaS config docs
  docs/fidesops/docs/saas_connectors/saas_config.md
Labels: documentation

#636 Fixing connector integration tests
  tests/integration_tests/saas/test_sentry_task.py
Labels: run unsafe ci checks

#619 [SaaS Connector] Outreach (Erasures)
  CHANGELOG.md
  data/saas/config/outreach_config.yml
  data/saas/dataset/outreach_dataset.yml
  saas_config.toml
  src/fidesops/schemas/saas/saas_config.py
  tests/fixtures/saas/outreach_fixtures.py
  tests/integration_tests/saas/test_outreach_task.py
Labels: enhancement, SaaSConnector

#641 Add ConnectionConfig Search [#609]
  CHANGELOG.md
  docs/fidesops/docs/guides/database_connectors.md
  src/fidesops/api/v1/endpoints/connection_endpoints.py
  src/fidesops/migrations/versions/b3b68c87c4a0_add_connection_config_description.py
  src/fidesops/models/connectionconfig.py
  src/fidesops/schemas/connection_configuration/connection_config.py
  tests/api/v1/endpoints/test_connection_config_endpoints.py
  tests/api/v1/endpoints/test_policy_webhook_endpoints.py
  tests/fixtures/postgres_fixtures.py
Labels: run unsafe ci checks

#664 Install MSSQL Dependencies by Default [#635]
  CHANGELOG.md
  Dockerfile
  run_infrastructure.py
Labels: run unsafe ci checks

#709 Remove stray hyphen
  docs/fidesops/docs/guides/configuration_reference.md
Labels: documentation

#676 [SaaS Connector] Salesforce (access)
  .github/workflows/unsafe_pr_checks.yml
  CHANGELOG.md
  Makefile
  data/saas/config/salesforce_config.yml
  data/saas/dataset/salesforce_dataset.yml
  pytest.ini
  saas_config.toml
  tests/conftest.py
  tests/fixtures/saas/hubspot_fixtures.py
  tests/fixtures/saas/salesforce_fixtures.py
  tests/fixtures/saas/segment_fixtures.py
  tests/integration_tests/saas/test_salesforce_task.py
  tests/integration_tests/saas/test_segment_task.py
  tests/integration_tests/saas/test_sentry_task.py
  tests/integration_tests/saas/test_zendesk_task.py
  tests/test_helpers/saas_test_utils.py
Labels: run unsafe ci checks
