Repository ethyca/fidesops, pull requests merged in 2022-04, with the labels that each got.

#340 Add Sentry Support [#256]
  .github/workflows/unsafe_pr_checks.yml
  Makefile
  data/saas/config/sentry_config.yml
  data/saas/dataset/sentry_dataset.yml
  docs/fidesops/docs/guides/saas_config.md
  docs/fidesops/docs/guides/saas_pagination.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  pytest.ini
  saas_config.toml
  src/fidesops/service/connectors/saas_connector.py
  tests/conftest.py
  tests/fixtures/saas/sentry_fixtures.py
  tests/integration_tests/saas/test_sentry_task.py
  tests/integration_tests/test_saas_task.py
Labels: run unsafe ci checks

#356 Update Privacy Request Search Mechanics
  docs/fidesops/docs/guides/reporting.md
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
Labels: run unsafe ci checks

#351 253 - Hubspot Connector (Access)
  .github/workflows/unsafe_pr_checks.yml
  Makefile
  data/saas/config/hubspot_config.yml
  data/saas/dataset/hubspot_dataset.yml
  docs/fidesops/docs/guides/saas_config.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  docs/fidesops/docs/tutorial/annotate_datasets.md
  docs/fidesops/docs/tutorial/define_policy.md
  docs/fidesops/docs/tutorial/execute_privacy_request.md
  docs/fidesops/docs/tutorial/oauth_client.md
  docs/fidesops/docs/tutorial/storage_config.md
  pytest.ini
  saas_config.toml
  src/fidesops/models/datasetconfig.py
  src/fidesops/schemas/saas/shared_schemas.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  src/fidesops/service/pagination/pagination_strategy_cursor.py
  src/fidesops/service/pagination/pagination_strategy_link.py
  src/fidesops/service/pagination/pagination_strategy_offset.py
  src/fidesops/util/url_util.py
  tests/conftest.py
  tests/fixtures/saas/hubspot_fixtures.py
  tests/fixtures/saas/mailchimp_fixtures.py
  tests/fixtures/saas_fixtures.py
  tests/integration_tests/saas/test_hubspot_task.py
  tests/service/connectors/test_queryconfig.py
  tests/service/privacy_request/request_runner_service_test.py
Labels: run unsafe ci checks

#350 Add Segment SaaS Connector + Authentication per Request [#251]
  .github/workflows/unsafe_pr_checks.yml
  Makefile
  data/saas/config/segment_config.yml
  data/saas/dataset/segment_dataset.yml
  docs/fidesops/docs/guides/saas_config.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  pytest.ini
  saas_config.toml
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/pagination/pagination_strategy_link.py
  tests/conftest.py
  tests/fixtures/saas/segment_fixtures.py
  tests/fixtures/saas/sentry_fixtures.py
  tests/integration_tests/saas/test_segment_task.py
  tests/integration_tests/saas/test_sentry_task.py
  tests/integration_tests/test_connection_configuration_integration.py
  tests/service/pagination/test_pagination_strategy_link.py
Labels: run unsafe ci checks

#362 Admin UI Backend Tweaks
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/schemas/privacy_request.py
  src/fidesops/schemas/user.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
  tests/fixtures/application_fixtures.py
Labels: run unsafe ci checks

#355 Stripe Connector (Access)
  .github/workflows/unsafe_pr_checks.yml
  Makefile
  data/saas/config/saas_example_config.yml
  data/saas/config/stripe_config.yml
  data/saas/dataset/stripe_dataset.yml
  docs/fidesops/docs/guides/saas_config.md
  pytest.ini
  saas_config.toml
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/saas_query_config.py
  tests/conftest.py
  tests/fixtures/saas/stripe_fixtures.py
  tests/integration_tests/saas/test_stripe_task.py
  tests/models/test_saasconfig.py
Labels: run unsafe ci checks

#370 [SaaS Connectors] Demonstrate Sentry Masking [#343]
  .github/workflows/unsafe_pr_checks.yml
  Makefile
  saas_config.toml
  tests/fixtures/saas/sentry_fixtures.py
  tests/integration_tests/saas/test_sentry_task.py
Labels: run unsafe ci checks

#375 Segment Masking Test Failures
  tests/integration_tests/saas/test_segment_task.py
  tests/integration_tests/saas/test_sentry_task.py
Labels: run unsafe ci checks

#364 #297 Admin UI v0
  clients/admin-ui/.babelrc
  clients/admin-ui/.env.development
  clients/admin-ui/.eslintrc.json
  clients/admin-ui/.gitignore
  clients/admin-ui/LICENSE
  clients/admin-ui/README.md
  clients/admin-ui/__tests__/index.test.tsx
  clients/admin-ui/__tests__/jest.setup.ts
  clients/admin-ui/jest.config.js
  clients/admin-ui/next-env.d.ts
  clients/admin-ui/next.config.js
  clients/admin-ui/package-lock.json
  clients/admin-ui/package.json
  clients/admin-ui/public/favicon.ico
  clients/admin-ui/public/logo-icon.svg
  clients/admin-ui/public/logo.svg
  clients/admin-ui/src/app/hooks.ts
  clients/admin-ui/src/app/store.ts
  clients/admin-ui/src/features/common/Header.tsx
  clients/admin-ui/src/features/common/Icon/ArrowDownLine.tsx
  clients/admin-ui/src/features/common/Icon/CloseSolid.tsx
  clients/admin-ui/src/features/common/Icon/DownloadSolid.tsx
  clients/admin-ui/src/features/common/Icon/Gear.tsx
  clients/admin-ui/src/features/common/Icon/More.tsx
  clients/admin-ui/src/features/common/Icon/SearchLine.tsx
  clients/admin-ui/src/features/common/Icon/User.tsx
  clients/admin-ui/src/features/common/Icon/index.tsx
  clients/admin-ui/src/features/privacy-requests/PIIToggle.tsx
  clients/admin-ui/src/features/privacy-requests/RequestBadge.tsx
  clients/admin-ui/src/features/privacy-requests/RequestFilters.tsx
  clients/admin-ui/src/features/privacy-requests/RequestRow.tsx
  clients/admin-ui/src/features/privacy-requests/RequestTable.tsx
  clients/admin-ui/src/features/privacy-requests/helpers.ts
  clients/admin-ui/src/features/privacy-requests/index.ts
  clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
  clients/admin-ui/src/features/privacy-requests/types.ts
  clients/admin-ui/src/features/user/index.ts
  clients/admin-ui/src/features/user/user.slice.ts
  clients/admin-ui/src/mocks/browser.ts
  clients/admin-ui/src/mocks/handlers.ts
  clients/admin-ui/src/mocks/index.ts
  clients/admin-ui/src/mocks/server.ts
  clients/admin-ui/src/pages/404.tsx
  clients/admin-ui/src/pages/_app.tsx
  clients/admin-ui/src/pages/api/auth/[...nextauth].ts
  clients/admin-ui/src/pages/index.tsx
  clients/admin-ui/src/pages/login.tsx
  clients/admin-ui/src/theme/index.ts
  clients/admin-ui/src/types/environment.d.ts
  clients/admin-ui/src/types/next-auth.d.ts
  clients/admin-ui/tsconfig.json
  clients/privacy-center/README.md
  fidesops.toml
Labels: run unsafe ci checks

#403 402 doc fixes
  docs/fidesops/docs/index.md
  docs/fidesops/docs/tutorial/define_policy.md
  docs/fidesops/docs/tutorial/execute_privacy_request.md
Labels: documentation

#435 [Misc DevOps] Make retry settings less onerous on CI
  docs/fidesops/docs/guides/configuration_reference.md
  fidesops.toml
Labels: run unsafe ci checks

#376 Validates date field ranges are sane
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
Labels: run unsafe ci checks

#443 update masking API to take multiple input values
  docs/fidesops/docs/guides/masking_strategies.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  src/fidesops/api/v1/endpoints/masking_endpoints.py
  src/fidesops/schemas/masking/masking_api.py
  src/fidesops/schemas/masking/masking_response.py
  src/fidesops/service/connectors/query_config.py
  src/fidesops/service/masking/strategy/masking_strategy.py
  src/fidesops/service/masking/strategy/masking_strategy_aes_encrypt.py
  src/fidesops/service/masking/strategy/masking_strategy_hash.py
  src/fidesops/service/masking/strategy/masking_strategy_hmac.py
  src/fidesops/service/masking/strategy/masking_strategy_nullify.py
  src/fidesops/service/masking/strategy/masking_strategy_random_string_rewrite.py
  src/fidesops/service/masking/strategy/masking_strategy_string_rewrite.py
  tests/api/v1/endpoints/test_masking_endpoints.py
  tests/service/connectors/test_queryconfig.py
  tests/service/masking/strategy/test_masking_strategy_aes_encrypt.py
  tests/service/masking/strategy/test_masking_strategy_hash.py
  tests/service/masking/strategy/test_masking_strategy_hmac.py
  tests/service/masking/strategy/test_masking_strategy_null.py
  tests/service/masking/strategy/test_masking_strategy_random_string_rewrite.py
  tests/service/masking/strategy/test_masking_strategy_string_rewrite.py
Labels: enhancement, Needs doc review
