Repository ethyca/fidesops, pull requests merged in 2022-08, with the labels that each got.

#986 saas request overrides
  CHANGELOG.md
  data/saas/config/request_override/mailchimp_override_config.yml
  data/saas/dataset/request_override/mailchimp_override_dataset.yml
  pytest.ini
  src/fidesops/common_exceptions.py
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  src/fidesops/service/saas_request/__init__.py
  src/fidesops/service/saas_request/override_implementations/__init__.py
  src/fidesops/service/saas_request/override_implementations/mailchimp_request_overrides.py
  src/fidesops/service/saas_request/saas_request_override_factory.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/request_override/__init__.py
  tests/ops/fixtures/saas/request_override/mailchimp_override_fixtures.py
  tests/ops/integration_tests/saas/request_override/__init__.py
  tests/ops/integration_tests/saas/request_override/test_mailchimp_override_task.py
  tests/ops/models/test_saasconfig.py
  tests/ops/service/saas_request/__init__.py
  tests/ops/service/saas_request/test_saas_request_override_factory.py
Labels: enhancement, dev experience, run unsafe ci checks, Needs doc review, fidesops-plus

#991 Added Auth0 Connector
  CHANGELOG.md
  data/saas/config/auth0_config.yml
  data/saas/dataset/auth0_dataset.yml
  pytest.ini
  saas_config.toml
  src/fidesops/schemas/saas/saas_config.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/auth0_fixtures.py
  tests/ops/integration_tests/saas/test_auth0_task.py
Labels: run unsafe ci checks

#966 Update the compose file and workflows to expect an already-built image
  .github/workflows/fidesops_safe_pr_checks.yml
  .github/workflows/fidesops_unsafe_pr_checks.yml
  .github/workflows/safe_pr_checks.yml
  .github/workflows/unsafe_pr_checks.yml
  CHANGELOG.md
  Makefile
  dev-requirements.txt
  docker-compose.yml
  noxfiles/ci_nox.py
  noxfiles/dev_nox.py
  noxfiles/run_infrastructure.py
  scripts/run_infrastructure.py
  src/fidesops/db/database.py
  src/fidesops/main.py
  src/fidesops/util/saas_util.py
Labels: run unsafe ci checks

#1039 Updating Salesforce to use OAuth2 authentication code flow
  data/saas/config/salesforce_config.yml
Labels: run unsafe ci checks

#1043 Removing saas_config.toml
  saas_config.toml
  tests/ops/fixtures/saas/adobe_campaign_fixtures.py
  tests/ops/fixtures/saas/auth0_fixtures.py
  tests/ops/fixtures/saas/hubspot_fixtures.py
  tests/ops/fixtures/saas/mailchimp_fixtures.py
  tests/ops/fixtures/saas/outreach_fixtures.py
  tests/ops/fixtures/saas/salesforce_fixtures.py
  tests/ops/fixtures/saas/segment_fixtures.py
  tests/ops/fixtures/saas/sendgrid_fixtures.py
  tests/ops/fixtures/saas/sentry_fixtures.py
  tests/ops/fixtures/saas/stripe_fixtures.py
  tests/ops/fixtures/saas/zendesk_fixtures.py
  tests/ops/fixtures/saas_example_fixtures.py
  tests/ops/integration_tests/saas/test_auth0_task.py
  tests/ops/integration_tests/saas/test_salesforce_task.py
Labels: run unsafe ci checks

#1040 Create finished audit log for privacy requests
  CHANGELOG.md
  requirements.txt
  src/fidesops/migrations/versions/bab75915670a_add_finished_audit_log.py
  src/fidesops/service/privacy_request/request_runner_service.py
  tests/ops/integration_tests/test_external_database_connections.py
  tests/ops/models/test_client.py
  tests/ops/service/privacy_request/request_runner_service_test.py
  tests/ops/service/storage_uploader_service_test.py
Labels: run unsafe ci checks

#1063 Release v1.7.0 Checklist
  CHANGELOG.md
Labels: run unsafe ci checks

#1070 Patch versioneer to allow editable installs
  CHANGELOG.md
  versioneer.py
Labels: bug, dependencies, Tech Debt, python

#1060 797 datadog
  CHANGELOG.md
  data/saas/config/datadog_config.yml
  data/saas/dataset/datadog_dataset.yml
  pytest.ini
  saas_config.toml
  src/fidesops/ops/schemas/saas/saas_config.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/datadog_fixtures.py
  tests/ops/integration_tests/saas/test_datadog_task.py
Labels: run unsafe ci checks

#1074 515 SaaS connector Logi ID
  CHANGELOG.md
  data/saas/config/logi_id_config.yml
  data/saas/dataset/logi_id_dataset.yml
  pytest.ini
  saas_config.toml
  src/fidesops/ops/schemas/saas/saas_config.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/conftest.py
  tests/ops/fixtures/saas/logi_id_fixtures.py
  tests/ops/integration_tests/saas/test_logi_id_task.py
Labels: run unsafe ci checks

#1075 Notify fidesdemo on new releases
  .github/workflows/release_event.yml
  CHANGELOG.md
Labels: enhancement, dev experience, github_actions

#1114 Formatting Issues in Webhooks Documentation
  CHANGELOG.md
  docs/fidesops/docs/guides/policy_webhooks.md
Labels: documentation

#1091 Update hubspot users and owners configurations
  CHANGELOG.md
  data/saas/config/hubspot_config.yml
  data/saas/dataset/hubspot_dataset.yml
  docs/fidesops/docs/saas_connectors/example_configs/hubspot.md
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
  tests/ops/fixtures/saas/hubspot_fixtures.py
  tests/ops/integration_tests/saas/test_hubspot_task.py
  tests/ops/service/privacy_request/request_runner_service_test.py
Labels: enhancement, run unsafe ci checks

#1166 SaaS Connector Template Creation Fix: Integer fides_key
  CHANGELOG.md
  src/fidesops/ops/util/saas_util.py
  tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
Labels: bug

#1223 [#1222] Fix reference in data categories upgrade migration
  src/fidesops/ops/migrations/versions/7abe778b7082_update_fideslang_data_categories.py
Labels: bug

#1174 Make log send async
  CHANGELOG.md
  dev-requirements.txt
  pyproject.toml
  src/fidesops/main.py
  src/fidesops/ops/analytics.py
  src/fidesops/ops/api/v1/endpoints/drp_endpoints.py
  src/fidesops/ops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/ops/graph/analytics_events.py
  src/fidesops/ops/service/privacy_request/request_runner_service.py
  src/fidesops/ops/task/graph_task.py
  src/fidesops/ops/util/wrappers.py
  tests/ops/conftest.py
  tests/ops/integration_tests/saas/request_override/test_mailchimp_override_task.py
  tests/ops/integration_tests/saas/test_adobe_campaign_task.py
  tests/ops/integration_tests/saas/test_auth0_task.py
  tests/ops/integration_tests/saas/test_datadog_task.py
  tests/ops/integration_tests/saas/test_hubspot_task.py
  tests/ops/integration_tests/saas/test_logi_id_task.py
  tests/ops/integration_tests/saas/test_mailchimp_task.py
  tests/ops/integration_tests/saas/test_outreach_task.py
  tests/ops/integration_tests/saas/test_salesforce_task.py
  tests/ops/integration_tests/saas/test_segment_task.py
  tests/ops/integration_tests/saas/test_sendgrid_task.py
  tests/ops/integration_tests/saas/test_sentry_task.py
  tests/ops/integration_tests/saas/test_stripe_task.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
  tests/ops/integration_tests/test_execution.py
  tests/ops/integration_tests/test_manual_task.py
  tests/ops/integration_tests/test_mongo_task.py
  tests/ops/integration_tests/test_sql_task.py
Labels: run unsafe ci checks
