Repository ethyca/fidesops, pull requests merged in 2022-05, with the labels that each got.

#448 Adding missing import
  src/fidesops/service/connectors/saas_connector.py
  tests/service/privacy_request/request_runner_service_test.py
Labels: run unsafe ci checks

#473 Fixing inconsistent SaaS connector integration tests
  src/fidesops/task/filter_results.py
  tests/fixtures/saas/hubspot_fixtures.py
  tests/fixtures/saas/segment_fixtures.py
  tests/fixtures/saas/sentry_fixtures.py
  tests/fixtures/saas/stripe_fixtures.py
  tests/integration_tests/saas/test_segment_task.py
  tests/integration_tests/saas/test_sentry_task.py
  tests/integration_tests/saas/test_stripe_task.py
Labels: run unsafe ci checks

#500 Fix error when editing user permissions
  src/fidesops/api/v1/endpoints/user_permission_endpoints.py
Labels: bug

#504 Refactoring SaaS authentication in preparation for OAuth2
  data/saas/config/hubspot_config.yml
  data/saas/config/mailchimp_config.yml
  data/saas/config/saas_example_config.yml
  data/saas/config/segment_config.yml
  data/saas/config/sentry_config.yml
  data/saas/config/stripe_config.yml
  docs/fidesops/docs/guides/saas_config.md
  docs/fidesops/docs/guides/saas_postprocessors.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  docs/fidesops/docs/sass_connectors.md
  src/fidesops/schemas/saas/strategy_configuration.py
  src/fidesops/service/authentication/__init__.py
  src/fidesops/service/authentication/authentication_strategy.py
  src/fidesops/service/authentication/authentication_strategy_basic.py
  src/fidesops/service/authentication/authentication_strategy_bearer.py
  src/fidesops/service/authentication/authentication_strategy_factory.py
  src/fidesops/service/authentication/authentication_strategy_query_param.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  src/fidesops/util/saas_util.py
  tests/fixtures/saas/segment_fixtures.py
  tests/service/authentication/test_authentication_strategy_basic.py
  tests/service/authentication/test_authentication_strategy_bearer.py
  tests/service/authentication/test_authentication_strategy_factory.py
  tests/service/authentication/test_authentication_strategy_query_param.py
  tests/service/connectors/test_saas_connector.py
  tests/util/test_saas_util.py
Labels: maintenance

#553 Add missing `__init__.py` file to `drp`
  src/fidesops/service/drp/__init__.py
Labels: bug, run unsafe ci checks

#498 Add teardown to make commands
  CHANGELOG.md
  Makefile
Labels: run unsafe ci checks

#560 refactor masking strategy factory for improved extensibility
  CHANGELOG.md
  docs/fidesops/docs/guides/masking_strategies.md
  src/fidesops/api/v1/endpoints/masking_endpoints.py
  src/fidesops/models/policy.py
  src/fidesops/service/connectors/query_config.py
  src/fidesops/service/masking/__init__.py
  src/fidesops/service/masking/strategy/masking_strategy_aes_encrypt.py
  src/fidesops/service/masking/strategy/masking_strategy_factory.py
  src/fidesops/service/masking/strategy/masking_strategy_hash.py
  src/fidesops/service/masking/strategy/masking_strategy_hmac.py
  src/fidesops/service/masking/strategy/masking_strategy_nullify.py
  src/fidesops/service/masking/strategy/masking_strategy_random_string_rewrite.py
  src/fidesops/service/masking/strategy/masking_strategy_string_rewrite.py
  src/fidesops/service/privacy_request/request_service.py
  tests/api/v1/endpoints/test_masking_endpoints.py
  tests/api/v1/endpoints/test_policy_endpoints.py
  tests/fixtures/application_fixtures.py
  tests/models/test_policy.py
  tests/service/connectors/test_queryconfig.py
  tests/service/masking/strategy/test_masking_strategy_aes_encrypt.py
  tests/service/masking/strategy/test_masking_strategy_factory.py
  tests/service/masking/strategy/test_masking_strategy_hash.py
  tests/service/masking/strategy/test_masking_strategy_hmac.py
  tests/service/privacy_request/request_runner_service_test.py
  tests/util/encryption/test_secrets_util.py
Labels: maintenance, dev experience, Needs doc review

#566 Add package directory config, include migrations in the PyPI package
  CHANGELOG.md
  MANIFEST.in
  create_superuser.py
  create_test_data.py
  src/fidesops/core/config.py
  src/fidesops/db/database.py
  src/fidesops/main.py
  tests/conftest.py
Labels: enhancement, dev experience, run unsafe ci checks
