Repository ethyca/fidesops, pull requests merged in 2022-03, with the labels that each got.

#229 Add Configuration Option for Entrypoint Array Querying [#193]
  README.md
  data/dataset/mongo_example_test_dataset.yml
  data/nosql/mongo-init.js
  docs/fidesops/docs/guides/complex_fields.md
  docs/fidesops/docs/guides/datasets.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  src/fidesops/graph/config.py
  src/fidesops/models/datasetconfig.py
  src/fidesops/schemas/dataset.py
  src/fidesops/task/filter_element_match.py
  src/fidesops/task/graph_task.py
  src/fidesops/task/refine_target_path.py
  tests/api/v1/endpoints/test_dataset_endpoints.py
  tests/fixtures/integration_fixtures.py
  tests/graph/test_config.py
  tests/integration_tests/test_mongo_task.py
  tests/models/test_datasetconfig.py
  tests/task/test_graph_task.py
  tests/task/traversal_data.py
  tests/util/test_dataset_yaml.py
Labels: run unsafe ci checks

#236 Fix Fields Affected on Execution Logs [#144]
  docs/fidesops/docs/guides/reporting.md
  src/fidesops/task/graph_task.py
  tests/integration_tests/test_mongo_task.py
  tests/task/test_graph_task.py
Labels: run unsafe ci checks

#233 182 api endpoints for saas
  data/saas/config/mailchimp_config.yml
  data/saas/dataset/mailchimp_dataset.yml
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  src/fidesops/api/v1/api.py
  src/fidesops/api/v1/endpoints/connection_endpoints.py
  src/fidesops/api/v1/endpoints/dataset_endpoints.py
  src/fidesops/api/v1/endpoints/saas_config_endpoints.py
  src/fidesops/api/v1/scope_registry.py
  src/fidesops/api/v1/urn_registry.py
  src/fidesops/common_exceptions.py
  src/fidesops/schemas/connection_configuration/connection_secrets_saas.py
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/saas_connector.py
  tests/api/v1/endpoints/test_connection_config_endpoints.py
  tests/api/v1/endpoints/test_dataset_endpoints.py
  tests/api/v1/endpoints/test_saas_config_endpoints.py
  tests/fixtures/saas_fixtures.py
  tests/integration_tests/test_connection_configuration_integration.py
  tests/schemas/connection_configuration/test_connection_secrets_saas.py
Labels: run unsafe ci checks

#237 176 mask data implementation
  data/saas/config/mailchimp_config.yml
  data/saas/config/stripe_config.yml
  data/saas/dataset/mailchimp_dataset.yml
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/query_config.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/util/saas_util.py
  tests/fixtures/application_fixtures.py
  tests/fixtures/saas_fixtures.py
  tests/integration_tests/test_saas_task.py
  tests/service/connectors/test_queryconfig.py
  tests/service/privacy_request/request_runner_service_test.py
  tests/util/test_saas_util.py
Labels: run unsafe ci checks

#246 177 - Saas connectors post processing
  data/saas/config/mailchimp_config.yml
  data/saas/dataset/mailchimp_dataset.yml
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  src/fidesops/common_exceptions.py
  src/fidesops/schemas/connection_configuration/__init__.py
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/schemas/saas/strategy_configuration.py
  src/fidesops/service/connectors/base_connector.py
  src/fidesops/service/connectors/http_connector.py
  src/fidesops/service/connectors/mongodb_connector.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/sql_connector.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_factory.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_filter.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_unwrap.py
  src/fidesops/task/graph_task.py
  tests/graph/graph_test_util.py
  tests/integration_tests/test_mongo_task.py
  tests/integration_tests/test_saas_task.py
  tests/integration_tests/test_sql_task.py
  tests/service/privacy_request/request_runner_service_test.py
  tests/service/processors/post_processor_strategy/__init__.py
  tests/service/processors/post_processor_strategy/test_post_processor_strategy_factory.py
  tests/service/processors/post_processor_strategy/test_post_processor_strategy_filter.py
  tests/service/processors/post_processor_strategy/test_post_processor_strategy_unwrap.py
Labels: run unsafe ci checks

#225 220 Documentation for setting up debugging in Jet Brains IDE.
  docs/fidesops/docs/development/jetbrains_debugging.md
  docs/fidesops/docs/img/ide/SDKs.png
  docs/fidesops/docs/img/ide/add_python_interpreter.png
  docs/fidesops/docs/img/ide/debug_config.png
  docs/fidesops/docs/img/ide/debugging.png
  docs/fidesops/docs/img/ide/docker.png
Labels: documentation

#259 SaaS connector docs
  data/saas/config/mailchimp_config.yml
  docs/fidesops/docs/guides/saas_config.md
  docs/fidesops/docs/guides/saas_connectors.md
  docs/fidesops/docs/guides/saas_postprocessors.md
  docs/fidesops/docs/postman/using_postman.md
  docs/fidesops/mkdocs.yml
Labels: run unsafe ci checks

#238 [#245] Allow unauthenticated creation of `PrivacyRequest`s
  docs/fidesops/docs/guides/privacy_requests.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  docs/fidesops/docs/tutorial/execute_privacy_request.md
  docs/fidesops/docs/tutorial/oauth_client.md
  quickstart.py
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/api/v1/scope_registry.py
  src/fidesops/models/privacy_request.py
  src/fidesops/schemas/privacy_request.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
  tests/models/test_privacy_request.py
Labels: run unsafe ci checks

#271 [Admin UI Backend] Adds User Model and Create/Delete User Endpoints
  Makefile
  create_superuser.py
  docs/fidesops/docs/development/contributing_details.md
  docs/fidesops/docs/img/app_database.png
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  run_infrastructure.py
  src/fidesops/api/v1/api.py
  src/fidesops/api/v1/endpoints/policy_endpoints.py
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/api/v1/endpoints/user_endpoints.py
  src/fidesops/api/v1/scope_registry.py
  src/fidesops/api/v1/urn_registry.py
  src/fidesops/db/base.py
  src/fidesops/models/client.py
  src/fidesops/models/fidesops_user.py
  src/fidesops/schemas/user.py
  src/migrations/env.py
  src/migrations/versions/5a966cd643d7_fidesops_user_and_client_detail.py
  tests/api/v1/endpoints/test_user_endpoints.py
  tests/fixtures/application_fixtures.py
  tests/models/test_fidesopsuser.py
  tests/scripts/test_create_superuser.py
Labels: run unsafe ci checks

#282 [Admin UI Backend] Add API Endpoints to Approve/Deny Privacy Requests
  docs/fidesops/docs/guides/configuration_reference.md
  docs/fidesops/docs/guides/privacy_requests.md
  docs/fidesops/docs/img/app_database.png
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  fidesops.toml
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/api/v1/scope_registry.py
  src/fidesops/api/v1/urn_registry.py
  src/fidesops/core/config.py
  src/fidesops/models/privacy_request.py
  src/fidesops/schemas/privacy_request.py
  src/migrations/versions/906d7198df28_privacy_request_approve.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
  tests/api/v1/endpoints/test_user_endpoints.py
  tests/fixtures/application_fixtures.py
Labels: run unsafe ci checks, Needs doc review

#279 Adds `include_identities` query param to `GET /api/v1/privacy-request`
  docs/fidesops/docs/guides/configuration_reference.md
  docs/fidesops/docs/guides/policy_webhooks.md
  docs/fidesops/docs/guides/reporting.md
  fidesops.toml
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/core/config.py
  src/fidesops/schemas/privacy_request.py
  src/fidesops/util/oauth_util.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
  tests/fixtures/application_fixtures.py
Labels: run unsafe ci checks, Needs doc review

#278 Cleaning up SaaS tests
  .github/workflows/unsafe_pr_checks.yml
  Makefile
  data/saas/config/saas_example_config.yml
  data/saas/dataset/saas_example_dataset.yml
  pytest.ini
  saas_config.toml
  tests/api/v1/endpoints/test_connection_config_endpoints.py
  tests/api/v1/endpoints/test_dataset_endpoints.py
  tests/api/v1/endpoints/test_saas_config_endpoints.py
  tests/fixtures/saas_fixtures.py
  tests/integration_tests/test_connection_configuration_integration.py
  tests/integration_tests/test_saas_task.py
  tests/models/test_saasconfig.py
  tests/schemas/connection_configuration/test_connection_secrets_saas.py
  tests/service/connectors/test_queryconfig.py
  tests/service/privacy_request/request_runner_service_test.py
  tests/util/test_saas_util.py
Labels: run unsafe ci checks

#285 [Admin UI Backend] Download privacy requests as CSV [#263]
  docs/fidesops/docs/guides/reporting.md
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/task/graph_task.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
Labels: run unsafe ci checks, Needs doc review

#286 262 saas connector pagination strategies
  data/saas/config/mailchimp_config.yml
  docs/fidesops/docs/guides/saas_config.md
  docs/fidesops/docs/guides/saas_pagination.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  docs/fidesops/mkdocs.yml
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/schemas/saas/shared_schemas.py
  src/fidesops/schemas/saas/strategy_configuration.py
  src/fidesops/service/connectors/query_config.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  src/fidesops/service/pagination/pagination_strategy.py
  src/fidesops/service/pagination/pagination_strategy_cursor.py
  src/fidesops/service/pagination/pagination_strategy_factory.py
  src/fidesops/service/pagination/pagination_strategy_link.py
  src/fidesops/service/pagination/pagination_strategy_offset.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_filter.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_unwrap.py
  tests/api/v1/endpoints/test_saas_config_endpoints.py
  tests/service/connectors/test_queryconfig.py
  tests/service/pagination/test_pagination_strategy_cursor.py
  tests/service/pagination/test_pagination_strategy_factory.py
  tests/service/pagination/test_pagination_strategy_link.py
  tests/service/pagination/test_pagination_strategy_offset.py
  tests/service/processors/post_processor_strategy/test_post_processor_strategy_unwrap.py
Labels: run unsafe ci checks

#283 272- adds support for custom http methods
  docs/fidesops/docs/guides/saas_config.md
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/schemas/saas/shared_schemas.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  src/fidesops/service/pagination/pagination_strategy_cursor.py
  src/fidesops/service/pagination/pagination_strategy_link.py
  src/fidesops/service/pagination/pagination_strategy_offset.py
  tests/fixtures/saas_fixtures.py
  tests/service/connectors/test_queryconfig.py
  tests/service/pagination/test_pagination_strategy_cursor.py
  tests/service/pagination/test_pagination_strategy_link.py
  tests/service/pagination/test_pagination_strategy_offset.py
  tests/service/privacy_request/request_runner_service_test.py
Labels: run unsafe ci checks

#309 Returning an empty list instead of None when post-processors filter a…
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_filter.py
  src/fidesops/service/processors/post_processor_strategy/post_processor_strategy_unwrap.py
  tests/service/processors/post_processor_strategy/test_post_processor_strategy_filter.py
  tests/service/processors/post_processor_strategy/test_post_processor_strategy_unwrap.py
Labels: run unsafe ci checks

#298 273- Adds support for request body in SaaS config
  docs/fidesops/docs/guides/saas_config.md
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/saas_query_config.py
  tests/service/connectors/test_queryconfig.py
Labels: run unsafe ci checks

#300 276 saas connector add the ability for request params to reference connector param values
  data/saas/config/saas_example_config.yml
  data/saas/dataset/saas_example_dataset.yml
  docs/fidesops/docs/guides/saas_config.md
  saas_config.toml
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  tests/api/v1/endpoints/test_saas_config_endpoints.py
  tests/fixtures/saas_fixtures.py
  tests/schemas/connection_configuration/test_connection_secrets_saas.py
  tests/service/connectors/test_queryconfig.py
Labels: run unsafe ci checks

#327 289 saas connector headers
  data/saas/config/mailchimp_config.yml
  data/saas/config/saas_example_config.yml
  docs/fidesops/docs/guides/saas_config.md
  docs/fidesops/docs/guides/saas_pagination.md
  docs/fidesops/docs/guides/saas_postprocessors.md
  docs/fidesops/docs/postman/Fidesops.postman_collection.json
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/schemas/saas/shared_schemas.py
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  src/fidesops/service/pagination/pagination_strategy_cursor.py
  src/fidesops/service/pagination/pagination_strategy_link.py
  src/fidesops/service/pagination/pagination_strategy_offset.py
  tests/api/v1/endpoints/test_saas_config_endpoints.py
  tests/fixtures/saas_fixtures.py
  tests/models/test_saasconfig.py
  tests/service/connectors/test_queryconfig.py
  tests/service/pagination/test_pagination_strategy_cursor.py
  tests/service/pagination/test_pagination_strategy_link.py
  tests/service/pagination/test_pagination_strategy_offset.py
  tests/service/privacy_request/request_runner_service_test.py
Labels: run unsafe ci checks

#306 Support Dependent Identity Data and "After" Param in Saas Configs [#291]
  data/saas/config/saas_example_config.yml
  data/saas/dataset/saas_example_dataset.yml
  docs/fidesops/docs/guides/saas_config.md
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/task/graph_task.py
  src/fidesops/util/saas_util.py
  tests/models/test_saasconfig.py
  tests/task/test_graph_task.py
  tests/task/traversal_data.py
Labels: run unsafe ci checks
