Repository ethyca/fidesops, pull requests merged in 2022-07, with the labels that each got.

#775 249 saas connector zendesk ticket erasure
  CHANGELOG.md
  data/saas/config/zendesk_config.yml
  data/saas/dataset/zendesk_dataset.yml
  tests/fixtures/saas/zendesk_fixtures.py
  tests/integration_tests/saas/test_segment_task.py
  tests/integration_tests/saas/test_zendesk_task.py
Labels: run unsafe ci checks

#830 Fix bug in client with no scopes
  CHANGELOG.md
  requirements.txt
  src/fidesops/api/v1/endpoints/oauth_endpoints.py
  src/fidesops/util/oauth_util.py
  tests/api/v1/endpoints/test_oauth_endpoints.py
Labels: DON'T MERGE

#835 adds concurrency to unsafe check jobs
  .github/workflows/unsafe_pr_checks.yml
Labels: run unsafe ci checks

#834 [#743] Store provided identity data in application database
  CHANGELOG.md
  create_test_data.py
  src/fidesops/api/v1/endpoints/drp_endpoints.py
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/migrations/versions/3c5e1253465d_adds_provided_identity_table_for_.py
  src/fidesops/models/privacy_request.py
  src/fidesops/service/drp/drp_fidesops_mapper.py
  src/fidesops/service/privacy_request/onetrust_service.py
  tests/api/v1/endpoints/test_drp_endpoints.py
  tests/api/v1/endpoints/test_privacy_request_endpoints.py
  tests/service/privacy_request/onetrust_test.py
Labels: run unsafe ci checks

#844 Populate dataset
  src/fidesops/graph/data_type.py
  tests/test_helpers/dataset_utils.py
  tests/test_helpers/test_dataset_utils.py
Labels: run unsafe ci checks

#869 Feat: Vault for secrets
  .github/workflows/unsafe_pr_checks.yml
  CHANGELOG.md
  Makefile
  requirements.txt
  tests/api/v1/endpoints/test_connection_config_endpoints.py
  tests/fixtures/saas/hubspot_fixtures.py
  tests/fixtures/saas/mailchimp_fixtures.py
  tests/fixtures/saas/outreach_fixtures.py
  tests/fixtures/saas/salesforce_fixtures.py
  tests/fixtures/saas/segment_fixtures.py
  tests/fixtures/saas/sentry_fixtures.py
  tests/fixtures/saas/stripe_fixtures.py
  tests/fixtures/saas/zendesk_fixtures.py
  tests/integration_tests/saas/test_salesforce_task.py
  tests/service/connectors/test_saas_connector.py
  tests/test_helpers/vault_client.py
Labels: run unsafe ci checks

#888 [SaaS Connector] Salesforce (erasure)
  CHANGELOG.md
  data/saas/config/salesforce_config.yml
  data/saas/dataset/salesforce_dataset.yml
  src/fidesops/service/connectors/saas_query_config.py
  src/fidesops/util/saas_util.py
  tests/fixtures/saas/salesforce_fixtures.py
  tests/integration_tests/saas/test_salesforce_task.py
  tests/util/test_saas_util.py
Labels: run unsafe ci checks

#883 252 saas connector sendgrid
  .github/workflows/unsafe_pr_checks.yml
  CHANGELOG.md
  data/saas/config/sendgrid_config.yml
  data/saas/dataset/sendgrid_dataset.yml
  pytest.ini
  saas_config.toml
  src/fidesops/schemas/saas/saas_config.py
  tests/conftest.py
  tests/fixtures/saas/sendgrid_fixtures.py
  tests/integration_tests/saas/test_sendgrid_task.py
Labels: run unsafe ci checks

#904 Adds saas config base info to connection config responses
  CHANGELOG.md
  src/fidesops/schemas/connection_configuration/connection_config.py
  src/fidesops/schemas/saas/saas_config.py
  tests/api/v1/endpoints/test_connection_config_endpoints.py
  tests/api/v1/endpoints/test_policy_webhook_endpoints.py
Labels: run unsafe ci checks

#911 Adding privacy_request_id placeholder
  CHANGELOG.md
  data/saas/config/saas_example_config.yml
  data/saas/dataset/saas_example_dataset.yml
  src/fidesops/service/connectors/saas_connector.py
  src/fidesops/service/connectors/saas_query_config.py
  tests/api/v1/endpoints/test_saas_config_endpoints.py
  tests/service/connectors/test_queryconfig.py
Labels: run unsafe ci checks

#905 Adobe Campaign access and erasure
  CHANGELOG.md
  data/saas/config/adobe_campaign_config.yml
  data/saas/dataset/adobe_campaign_dataset.yml
  pytest.ini
  src/fidesops/schemas/saas/saas_config.py
  src/fidesops/service/connectors/saas_connector.py
  tests/conftest.py
  tests/fixtures/saas/adobe_campaign_fixtures.py
  tests/integration_tests/saas/test_adobe_campaign_task.py
  tests/test_helpers/vault_client.py
Labels: run unsafe ci checks

#772 Updated tutorial to match latest fidesdemo
  docs/fidesops/docs/tutorial/installation.md
Labels: documentation

#928 Update python docker base image from slim-buster to slim-bullseye
  CHANGELOG.md
  Dockerfile
  dev-requirements.txt
Labels: run unsafe ci checks

#945 Dispatch a repository event on new published releases
  .github/workflows/release_event.yml
  CHANGELOG.md
Labels: dev experience, Tech Debt, fidesops-plus, github_actions

#944 Reduce # of clients connected to the application db [#810]
  CHANGELOG.md
  src/fidesops/api/v1/endpoints/privacy_request_endpoints.py
  src/fidesops/service/privacy_request/request_runner_service.py
  src/fidesops/task/graph_task.py
  src/fidesops/task/task_resources.py
  src/fidesops/tasks/__init__.py
  tests/ops/graph/test_graph.py
  tests/ops/integration_tests/saas/test_adobe_campaign_task.py
  tests/ops/integration_tests/saas/test_hubspot_task.py
  tests/ops/integration_tests/saas/test_mailchimp_task.py
  tests/ops/integration_tests/saas/test_outreach_task.py
  tests/ops/integration_tests/saas/test_salesforce_task.py
  tests/ops/integration_tests/saas/test_segment_task.py
  tests/ops/integration_tests/saas/test_sendgrid_task.py
  tests/ops/integration_tests/saas/test_sentry_task.py
  tests/ops/integration_tests/saas/test_stripe_task.py
  tests/ops/integration_tests/saas/test_zendesk_task.py
  tests/ops/integration_tests/test_execution.py
  tests/ops/integration_tests/test_manual_task.py
  tests/ops/integration_tests/test_mongo_task.py
  tests/ops/integration_tests/test_sql_task.py
  tests/ops/task/test_graph_task.py
  tests/ops/task/test_task_resources.py
Labels: run unsafe ci checks
